[project]
name = "project2"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "bentoml>=1.4.30",
    "numpy>=2.3.5",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
